### ISSUE TITLE
update_setting...keyError: 'ua_path'

### ISSUE THREAD

**Issue by Zenya393** [frenchcutgreenbean/UNIT3D-Upload-Checker#7]
When executing the command:
`# ./check.py save`

Receive error message:

```
Traceback (most recent call last):
  File "/home/uploadchecker/UNIT3D-Upload-Checker/./check.py", line 884, in <module>
    ch = UploadChecker()
         ^^^^^^^^^^^^^^^
  File "/home/uploadchecker/UNIT3D-Upload-Checker/./check.py", line 36, in __init__
    self.update_settings()
  File "/home/uploadchecker/UNIT3D-Upload-Checker/./check.py", line 846, in update_settings
    self.ua_path = self.current_settings["ua_path"]
                   ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'ua_path'
```

Solution:
Needed to add this line to the settings.py file:
`"ua_path": "",`

**Comment by Zenya393** [comment]
There was an upgrade that required the following line to be added to my settings.json file.

`"ua_path": "",`

If there's a better way of knowing the settings.json file has changed, please let me know.
